// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://engqntmzqjktopvgnvfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuZ3FudG16cWprdG9wdmdudmZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTc1MTEsImV4cCI6MjA2NDMzMzUxMX0.KkwI6x1tAY5-ZOQqKM_PYb6BrmFmkmyCnuVGxdFtFrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);